#!/bin/sh
#PBS -l walltime=148:00:00
#PBS -l select=1:ncpus=1:mem=4GB
#PBS -q pqberloff

# Serial
module load intel-suite
module load fftw
export NETCDF_VERSION=4.3.3                
module load netcdf/$NETCDF_VERSION  
module load mpi      

cp /rds/general/user/rk2014/home/WORK/cabaret_data/d/QG_new.nc ${TMPDIR}

time ${WORK}/advection/advection3layer/BUILD/offline_transport3layer

cp ${TMPDIR}/full_uniform_bins_trajectories.nc /rds/general/user/rk2014/home/WORK/advection_data/test/
