#!/bin/sh
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=1:mem=4GB

# Serial
module load intel-suite
module load fftw/3.1.1-double
export NETCDF_VERSION=4.3.3
module load netcdf/$NETCDF_VERSION

cp ${WORK}/cabaret/qg_513_s ${WORK}/cabaret/stratification.d ${TMPDIR}

cd ${TMPDIR}

time ${WORK}/cabaret/BUILD/qg3netcdf_DG_1025

cp -r ${TMPDIR}/. /rds/general/user/rk2014/home/WORK/cabaret_data/test/
